#pragma once

typedef enum Symbol_Type {
    TERMINAL,
    NON_TERMINAL,
} Symbol_Type;

typedef enum {
    NON_TERMINAL_PROG = 400,
    NON_TERMINAL_BLOCK,
    NON_TERMINAL_STMT_LIST,
    NON_TERMINAL_STMT,
    NON_TERMINAL_VAR_DECL,
    NON_TERMINAL_TYPE,
    NON_TERMINAL_ASSIGN_STMT,
    NON_TERMINAL_LVAL,
    NON_TERMINAL_IO_STMT,
    NON_TERMINAL_CTRL_FLOW,
    NON_TERMINAL_IF_STMT,
    NON_TERMINAL_ELIF_LIST,
    NON_TERMINAL_ELSE_PART,
    NON_TERMINAL_LOOP_STMT,
    NON_TERMINAL_FUNC_DECL,
    NON_TERMINAL_PARAM_LIST,
    NON_TERMINAL_FUNC_RET,
    NON_TERMINAL_FUNC_CALL_STMT,
    NON_TERMINAL_FUNC_CALL,
    NON_TERMINAL_ARG_LIST,
    NON_TERMINAL_E,
    NON_TERMINAL_T,
    NON_TERMINAL_F,
    NON_TERMINAL_COND,
    NON_TERMINAL_BOOL_T,
    NON_TERMINAL_BOOL_F,
    NON_TERMINAL_E_OP,
    NON_TERMINAL_T_OP,
    NON_TERMINAL_REL_OP
} NonTerminal;